#!/bin/bash
# Xen Hypervisor Installation Script for GCP GPU Instance
# This script installs Xen with GPU PCI passthrough support

set -e

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     Xen Hypervisor Installation for GPU Isolation        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root"
    exit 1
fi

# Backup original grub config
echo "=== Step 1: Backing up GRUB configuration ==="
cp /etc/default/grub /etc/default/grub.backup
echo "Backup created at /etc/default/grub.backup"
echo ""

# Install Xen hypervisor and tools
echo "=== Step 2: Installing Xen packages ==="
apt-get update -qq
apt-get install -y \
    xen-hypervisor-amd64 \
    xen-tools \
    xen-utils-common \
    xenstore-utils \
    libxen-dev \
    libxenstore3.0
echo "Xen packages installed"
echo ""

# Configure GRUB for Xen
echo "=== Step 3: Configuring GRUB to boot Xen ==="
cat > /etc/default/grub.d/xen.cfg <<'EOF'
# Xen Hypervisor GRUB Configuration
GRUB_DEFAULT="Xen hypervisor"
GRUB_TIMEOUT=5
GRUB_CMDLINE_XEN_DEFAULT="dom0_mem=4096M,max:4096M dom0_max_vcpus=4 iommu=1"
GRUB_CMDLINE_LINUX_XEN_REPLACE="console=hvc0 earlyprintk=xen"
EOF

# Enable IOMMU for PCI passthrough
echo "Enabling IOMMU in GRUB..."
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& intel_iommu=on iommu=pt/' /etc/default/grub

update-grub
echo "GRUB configured"
echo ""

# Configure Xen for GPU passthrough
echo "=== Step 4: Configuring Xen for GPU PCI Passthrough ==="
cat > /etc/xen/xl.conf <<'EOF'
# Xen Toolstack Configuration
autoballoon="off"
lockfile="/var/lock/xl"
vif.default.script="vif-bridge"
vif.default.bridge="xenbr0"
EOF

echo "Xen configuration complete"
echo ""

# Create systemd service for GPU proxy daemon
echo "=== Step 5: Creating GPU Proxy systemd service ==="
cat > /etc/systemd/system/gpu-proxy.service <<'EOF'
[Unit]
Description=GPU Proxy Daemon for Xen Isolation
After=network.target xen-qemu-dom0-disk-backend.service xenconsoled.service

[Service]
Type=simple
ExecStart=/opt/gpu-proxy/gpu_proxy
Restart=always
RestartSec=3
User=root
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
echo "GPU Proxy service created (will be enabled after binary installation)"
echo ""

# Get GPU PCI address
echo "=== Step 6: Detecting GPU PCI Address ==="
GPU_PCI=$(lspci | grep -i nvidia | grep -i vga | awk '{print $1}')
if [ -z "$GPU_PCI" ]; then
    echo "WARNING: No NVIDIA GPU detected!"
    echo "PCI passthrough may not work."
else
    echo "NVIDIA GPU detected at PCI address: $GPU_PCI"

    # Convert to Xen PCI format (0000:xx:yy.z)
    XEN_PCI="0000:$GPU_PCI"
    echo "Xen PCI address: $XEN_PCI"

    # Create helper file for domain configs
    echo "$XEN_PCI" > /etc/xen/gpu-pci-address
    echo "GPU PCI address saved to /etc/xen/gpu-pci-address"
fi
echo ""

# Create network bridge for domains
echo "=== Step 7: Setting up Xen network bridge ==="
apt-get install -y bridge-utils

# Check if bridge already exists
if ! brctl show | grep -q xenbr0; then
    cat > /etc/network/interfaces.d/xenbr0 <<'EOF'
auto xenbr0
iface xenbr0 inet dhcp
    bridge_ports eth0
    bridge_stp off
    bridge_fd 0
    bridge_maxwait 0
EOF
    echo "Network bridge configured (will be active after reboot)"
else
    echo "Bridge xenbr0 already exists"
fi
echo ""

# Create directory for domain configs
echo "=== Step 8: Setting up domain configuration directory ==="
mkdir -p /etc/xen/domains
mkdir -p /opt/gpu-proxy
echo "Directories created"
echo ""

# Create test domain configuration template
echo "=== Step 9: Creating test domain template ==="
cat > /etc/xen/domains/test-domain.cfg <<'EOF'
# Test Xen Domain Configuration
# This is a template - actual configs will be generated by CRI runtime

name = "test-domain"
type = "pvh"  # Paravirtualized with HVM extensions
memory = 2048
vcpus = 2
kernel = "/boot/vmlinuz"
ramdisk = "/boot/initrd.img"

# Root filesystem (will be container image rootfs)
root = "/dev/xvda ro"
disk = [ 'file:/var/lib/xen/images/test.img,xvda,w' ]

# Network
vif = [ 'bridge=xenbr0' ]

# Console
on_poweroff = 'destroy'
on_reboot = 'restart'
on_crash = 'restart'
EOF
echo "Test domain template created at /etc/xen/domains/test-domain.cfg"
echo ""

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     Xen Installation Complete!                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "IMPORTANT: System reboot required to boot into Xen hypervisor"
echo ""
echo "Next steps:"
echo "  1. Reboot the system: sudo reboot"
echo "  2. After reboot, verify Xen is running: xl info"
echo "  3. Check GPU PCI device: lspci | grep NVIDIA"
echo "  4. Compile IDM protocol with USE_XEN flag"
echo "  5. Install GPU proxy binary to /opt/gpu-proxy/"
echo "  6. Enable GPU proxy service: systemctl enable --now gpu-proxy"
echo ""
echo "To manually boot into Xen (if needed):"
echo "  - At GRUB menu, select 'Xen hypervisor'"
echo ""
